In [1]:
import pandas as pd

In [6]:
df=pd.read_csv(r"C:\Users\HP\Downloads\hospital_admissions_data.csv")

In [7]:
df.head()

,admission_id,patient_id,admission_date,department,diagnosis,age,gender,insurance_type,admission_type,length_of_stay_days,billing_amount,discharge_status,is_readmission_30d,patient_satisfaction
0,ADM306377,PT24506,2024-01-01,General Medicine,Diabetes Mellitus,69,Male,Corporate Insurance,Referral,5,35516.43,Recovered,False,5.0
1,ADM304754,PT23379,2024-01-01,General Medicine,Viral Fever,58,Female,Self-Pay,Emergency,5,37382.32,Recovered,False,4.0
2,ADM311557,PT28133,2024-01-01,Gynecology,C-Section,34,Male,Self-Pay,Elective,5,41269.39,Recovered,False,2.0
3,ADM309559,PT26701,2024-01-01,Cardiology,Hypertension,72,Male,Self-Pay,Referral,2,64657.99,Recovered,False,3.0
4,ADM300616,PT20457,2024-01-01,Emergency,Acute Abdomen,60,Female,Corporate Insurance,Elective,4,27881.82,Recovered,False,5.0

In [9]:
df.shape

(13266, 14)

In [11]:
df.columns

Index(['admission_id', 'patient_id', 'admission_date', 'department',
       'diagnosis', 'age', 'gender', 'insurance_type', 'admission_type',
       'length_of_stay_days', 'billing_amount', 'discharge_status',
       'is_readmission_30d', 'patient_satisfaction'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13266 entries, 0 to 13265
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   admission_id          13266 non-null  object
 1   patient_id            13266 non-null  object
 2   admission_date        13266 non-null  object
 3   department            13266 non-null  object
 4   diagnosis             13266 non-null  object
 5   age                   13266 non-null  int64
 6   gender                13266 non-null  object
 7   insurance_type        13266 non-null  object
 8   admission_type        13266 non-null  object
 9   length_of_stay_days   13266 non-null  int64
 10  billing_amount        13266 non-null  float64
 11  discharge_status      13266 non-null  object
 12  is_readmission_30d    13266 non-null  bool
 13  patient_satisfaction  13011 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(9)
memory usage: 1.3+ MB

In [14]:
df.isnull().sum()

admission_id              0
patient_id                0
admission_date            0
department                0
diagnosis                 0
age                       0
gender                    0
insurance_type            0
admission_type            0
length_of_stay_days       0
billing_amount            0
discharge_status          0
is_readmission_30d        0
patient_satisfaction    255
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df[df["patient_satisfaction"].isnull()].head()

,admission_id,patient_id,admission_date,department,diagnosis,age,gender,insurance_type,admission_type,length_of_stay_days,billing_amount,discharge_status,is_readmission_30d,patient_satisfaction
26,ADM303221,PT22278,2024-01-02,Nephrology,UTI,71,Female,Self-Pay,Emergency,4,76419.22,Deceased,False,NaN
79,ADM310740,PT27550,2024-01-04,Nephrology,Chronic Kidney Disease,28,Female,Government Scheme,Emergency,7,125202.52,Deceased,False,NaN
83,ADM309930,PT26962,2024-01-04,Neurology,Stroke,12,Female,Corporate Insurance,Referral,9,105376.85,Deceased,False,NaN
107,ADM310613,PT27465,2024-01-06,Cardiology,Arrhythmia,10,Male,Self-Pay,Emergency,5,134373.14,Deceased,False,NaN
134,ADM308758,PT26150,2024-01-07,Emergency,Trauma,44,Female,Private Insurance,Referral,3,52311.56,Deceased,False,NaN

In [17]:
df["patient_satisfaction"].describe()

count    13011.000000
mean         3.759127
std          1.189924
min          1.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          5.000000
Name: patient_satisfaction, dtype: float64

In [18]:
df["patient_satisfaction"].unique()

array([ 5.,  4.,  2.,  3., nan,  1.])

In [20]:
df["admission_date"]=pd.to_datetime(df["admission_date"])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13266 entries, 0 to 13265
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   admission_id          13266 non-null  object
 1   patient_id            13266 non-null  object
 2   admission_date        13266 non-null  datetime64[ns]
 3   department            13266 non-null  object
 4   diagnosis             13266 non-null  object
 5   age                   13266 non-null  int64
 6   gender                13266 non-null  object
 7   insurance_type        13266 non-null  object
 8   admission_type        13266 non-null  object
 9   length_of_stay_days   13266 non-null  int64
 10  billing_amount        13266 non-null  float64
 11  discharge_status      13266 non-null  object
 12  is_readmission_30d    13266 non-null  bool
 13  patient_satisfaction  13011 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 1.3+ MB

In [22]:
df["admission_date"].min()

Timestamp('2024-01-01 00:00:00')

In [23]:
df["admission_date"].max()

Timestamp('2025-12-31 00:00:00')