In [2]:
import pandas as pd

patients = pd.read_csv("patients.csv")
services = pd.read_csv("services_weekly.csv")
staff = pd.read_csv("staff.csv")
schedule = pd.read_csv("staff_schedule.csv")

print("Patients:", patients.shape)
print("Services:", services.shape)
print("Staff:", staff.shape)
print("Schedule:", schedule.shape)

Patients: (1000, 7)
Services: (208, 10)
Staff: (110, 4)
Schedule: (6552, 6)

In [3]:
print("PATIENTS")
display(patients.head())

PATIENTS

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [4]:
print("Weekly Services")
display(services.head())

Weekly Services

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none

In [5]:
print("STAFF")
display(staff.head())

print("STAFF SCHEDULE")
display(schedule.head())

STAFF

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency

STAFF SCHEDULE

   week      staff_id    staff_name    role    service  present
0     1  STF-b77cdc60  Allison Hill  doctor  emergency        1
1     2  STF-b77cdc60  Allison Hill  doctor  emergency        1
2     3  STF-b77cdc60  Allison Hill  doctor  emergency        0
3     4  STF-b77cdc60  Allison Hill  doctor  emergency        1
4     5  STF-b77cdc60  Allison Hill  doctor  emergency        1

In [6]:
print(patients.isnull().sum())
print("Duplicates:", patients.duplicated().sum())

patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64
Duplicates: 0

In [7]:
print(services.isnull().sum())
print("Duplicates:", services.duplicated().sum())

print(staff.isnull().sum())
print("Duplicates:", staff.duplicated().sum())

print(schedule.isnull().sum())
print("Duplicates:", schedule.duplicated().sum())

week                    0
month                   0
service                 0
available_beds          0
patients_request        0
patients_admitted       0
patients_refused        0
patient_satisfaction    0
staff_morale            0
event                   0
dtype: int64
Duplicates: 0
staff_id      0
staff_name    0
role          0
service       0
dtype: int64
Duplicates: 0
week          0
staff_id      0
staff_name    0
role          0
service       0
present       0
dtype: int64
Duplicates: 0

In [8]:
print(patients.dtypes)
print(services.dtypes)
print(staff.dtypes)
print(schedule.dtypes)

patient_id          str
name                str
age               int64
arrival_date        str
departure_date      str
service             str
satisfaction      int64
dtype: object
week                    int64
month                   int64
service                   str
available_beds          int64
patients_request        int64
patients_admitted       int64
patients_refused        int64
patient_satisfaction    int64
staff_morale            int64
event                     str
dtype: object
staff_id      str
staff_name    str
role          str
service       str
dtype: object
week          int64
staff_id        str
staff_name      str
role            str
service         str
present       int64
dtype: object

In [9]:
patients["arrival_date"] = pd.to_datetime(patients["arrival_date"])
patients["departure_date"] = pd.to_datetime(patients["departure_date"])

print(patients.dtypes)

patient_id                   str
name                         str
age                        int64
arrival_date      datetime64[us]
departure_date    datetime64[us]
service                      str
satisfaction               int64
dtype: object

In [10]:
print("Invalid dates:",(patients["departure_date"] < patients["arrival_date"]).sum())

print("Same-day stays:",(patients["departure_date"] == patients["arrival_date"]).sum())

Invalid dates: 0
Same-day stays: 0

In [11]:
patients["length_of_stay"] = (patients["departure_date"] - patients["arrival_date"]).dt.days

print(patients[["patient_id", "length_of_stay"]].head())

     patient_id  length_of_stay
0  PAT-09484753               6
1  PAT-f0644084               1
2  PAT-ac6162e4               6
3  PAT-3dda2bb5              11
4  PAT-08591375               7

In [12]:
print("Negative stays:", (patients["length_of_stay"] < 0).sum())

Negative stays: 0

In [13]:
print(patients["service"].unique())
print(services["service"].unique())

<StringArray>
['surgery', 'general_medicine', 'emergency', 'ICU']
Length: 4, dtype: str
<StringArray>
['emergency', 'surgery', 'general_medicine', 'ICU']
Length: 4, dtype: str

In [14]:
print("Requests:", (services["patients_request"] < 0).sum())
print("Admissions:", (services["patients_admitted"] < 0).sum())
print("Refusals:", (services["patients_refused"] < 0).sum())
print("Beds:", (services["available_beds"] < 0).sum())

Requests: 0
Admissions: 0
Refusals: 0
Beds: 0

In [15]:
print(services[["patients_request", "patients_admitted", "patients_refused"]].head())

   patients_request  patients_admitted  patients_refused
0                76                 32                44
1               130                 45                85
2               201                 37               164
3                31                 22                 9
4               169                 28               141

In [16]:
print(schedule["present"].value_counts())

present
1    3930
0    2622
Name: count, dtype: int64

In [17]:
print("Invalid attendance values:", (~schedule["present"].isin([0, 1])).sum())

Invalid attendance values: 0

In [18]:
print(schedule["present"].value_counts())

present
1    3930
0    2622
Name: count, dtype: int64

In [19]:
print("Mismatched requests:",
      (services["patients_request"] !=
       services["patients_admitted"] +
       services["patients_refused"]).sum())

Mismatched requests: 0

In [20]:
print("Duplicate patient IDs:", patients["patient_id"].duplicated().sum())
print("Duplicate staff IDs:", staff["staff_id"].duplicated().sum())

Duplicate patient IDs: 0
Duplicate staff IDs: 0

In [22]:
patients["arrival_month"] = patients["arrival_date"].dt.month
patients["arrival_day"] = patients["arrival_date"].dt.day_name()

In [23]:
print(patients[["patient_id","length_of_stay","arrival_month","arrival_day"]].head())

     patient_id  length_of_stay  arrival_month arrival_day
0  PAT-09484753               6              3      Sunday
1  PAT-f0644084               1             12    Saturday
2  PAT-ac6162e4               6              6      Sunday
3  PAT-3dda2bb5              11             10      Sunday
4  PAT-08591375               7              2     Tuesday

In [24]:
patients.to_csv("patients_cleaned.csv", index=False)
services.to_csv("services_weekly_cleaned.csv", index=False)
staff.to_csv("staff_cleaned.csv", index=False)
schedule.to_csv("staff_schedule_cleaned.csv", index=False)

In [25]:
print(services.columns.tolist())
print(services.head())
print(staff.columns.tolist())
print(schedule.columns.tolist())

['week', 'month', 'service', 'available_beds', 'patients_request', 'patients_admitted', 'patients_refused', 'patient_satisfaction', 'staff_morale', 'event']
   week  month           service  available_beds  patients_request  \
0     1      1         emergency              32                76
1     1      1           surgery              45               130
2     1      1  general_medicine              37               201
3     1      1               ICU              22                31
4     2      1         emergency              28               169

   patients_admitted  patients_refused  patient_satisfaction  staff_morale  \
0                 32                44                    67            70
1                 45                85                    83            78
2                 37               164                    97            43
3                 22                 9                    84            91
4                 28               141                    75            64

  event
0  none
1   flu
2   flu
3   flu
4  none
['staff_id', 'staff_name', 'role', 'service']
['week', 'staff_id', 'staff_name', 'role', 'service', 'present']

In [26]:
patients["week"] = patients["arrival_date"].dt.isocalendar().week.astype(int)

In [27]:
patient_summary = patients.groupby(
    ["week", "service"]
).agg(
    patient_count=("patient_id", "count"),
    average_age=("age", "mean"),
    average_length_of_stay=("length_of_stay", "mean"),
    average_satisfaction=("satisfaction", "mean")
).reset_index()

In [28]:
print(patient_summary.shape)
print(patient_summary.head())

(208, 6)
   week           service  patient_count  average_age  average_length_of_stay  \
0     1               ICU              7        43.00                5.428571
1     1         emergency              4        42.25                9.250000
2     1  general_medicine              5        51.20                7.400000
3     1           surgery              6        50.00               10.000000
4     2               ICU              4        50.75                8.000000

   average_satisfaction
0             84.857143
1             86.000000
2             77.400000
3             84.666667
4             69.250000

In [29]:
staff_summary = staff.groupby(
    "service"
).agg(
    staff_count=("staff_id", "count")
).reset_index()

print(staff_summary)

            service  staff_count
0               ICU           32
1         emergency           29
2  general_medicine           27
3           surgery           22

In [30]:
staff_weekly = schedule.groupby(
    ["week", "service"]
).agg(
    staff_present=("present", "sum")
).reset_index()

print(staff_weekly.head())

   week           service  staff_present
0     1               ICU             31
1     1         emergency             35
2     1  general_medicine             27
3     1           surgery             23
4     2               ICU             30

In [31]:
hospital_raw = services.merge(
    patient_summary,
    on=["week", "service"],
    how="left"
)

print(hospital_raw.shape)
print(hospital_raw.head())

(208, 14)
   week  month           service  available_beds  patients_request  \
0     1      1         emergency              32                76
1     1      1           surgery              45               130
2     1      1  general_medicine              37               201
3     1      1               ICU              22                31
4     2      1         emergency              28               169

   patients_admitted  patients_refused  patient_satisfaction  staff_morale  \
0                 32                44                    67            70
1                 45                85                    83            78
2                 37               164                    97            43
3                 22                 9                    84            91
4                 28               141                    75            64

  event  patient_count  average_age  average_length_of_stay  \
0  none              4    42.250000                9.250000
1   flu              6    50.000000               10.000000
2   flu              5    51.200000                7.400000
3   flu              7    43.000000                5.428571
4  none              3    58.333333                6.000000

   average_satisfaction
0             86.000000
1             84.666667
2             77.400000
3             84.857143
4             74.000000

In [32]:
hospital_raw = hospital_raw.merge(
    staff_summary,
    on="service",
    how="left"
)

print(hospital_raw.shape)

(208, 15)

In [33]:
hospital_raw = hospital_raw.merge(
    staff_weekly,
    on=["week", "service"],
    how="left"
)

print(hospital_raw.shape)
print(hospital_raw.head())

(208, 16)
   week  month           service  available_beds  patients_request  \
0     1      1         emergency              32                76
1     1      1           surgery              45               130
2     1      1  general_medicine              37               201
3     1      1               ICU              22                31
4     2      1         emergency              28               169

   patients_admitted  patients_refused  patient_satisfaction  staff_morale  \
0                 32                44                    67            70
1                 45                85                    83            78
2                 37               164                    97            43
3                 22                 9                    84            91
4                 28               141                    75            64

  event  patient_count  average_age  average_length_of_stay  \
0  none              4    42.250000                9.250000
1   flu              6    50.000000               10.000000
2   flu              5    51.200000                7.400000
3   flu              7    43.000000                5.428571
4  none              3    58.333333                6.000000

   average_satisfaction  staff_count  staff_present
0             86.000000           29             35
1             84.666667           22             23
2             77.400000           27             27
3             84.857143           32             31
4             74.000000           29             37

In [34]:
print("Duplicate staff-week records:")
print(schedule.duplicated(["week", "staff_id"]).sum())

print("Total staff:", staff["staff_id"].nunique())
print("Scheduled staff:", schedule["staff_id"].nunique())

print("Staff IDs in schedule but not staff:")
print((~schedule["staff_id"].isin(staff["staff_id"])).sum())

Duplicate staff-week records:
0
Total staff: 110
Scheduled staff: 126
Staff IDs in schedule but not staff:
6552

In [35]:
staff_check = schedule.merge(
    staff,
    on=["staff_name", "role", "service"],
    how="left",
    indicator=True
)

print(staff_check["_merge"].value_counts())

_merge
left_only     4836
both          1716
right_only       0
Name: count, dtype: int64

In [36]:
unmatched = staff_check[
    staff_check["_merge"] == "left_only"
]

print(unmatched[
    ["staff_id_x", "staff_name", "role", "service", "week"]
].head(10))

       staff_id_x       staff_name    role    service  week
260  STF-bea9d5c9  Connie Lawrence  doctor  emergency     1
261  STF-bea9d5c9  Connie Lawrence  doctor  emergency     2
262  STF-bea9d5c9  Connie Lawrence  doctor  emergency     3
263  STF-bea9d5c9  Connie Lawrence  doctor  emergency     4
264  STF-bea9d5c9  Connie Lawrence  doctor  emergency     5
265  STF-bea9d5c9  Connie Lawrence  doctor  emergency     6
266  STF-bea9d5c9  Connie Lawrence  doctor  emergency     7
267  STF-bea9d5c9  Connie Lawrence  doctor  emergency     8
268  STF-bea9d5c9  Connie Lawrence  doctor  emergency     9
269  STF-bea9d5c9  Connie Lawrence  doctor  emergency    10

In [37]:
print(staff.head())

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency

In [38]:
schedule_names = set(schedule["staff_name"])
staff_names = set(staff["staff_name"])

print("Names only in schedule:", len(schedule_names - staff_names))
print("Names only in staff:", len(staff_names - schedule_names))

Names only in schedule: 16
Names only in staff: 0

In [39]:
staff_check = schedule.merge(
    staff,
    on="staff_name",
    how="left",
    suffixes=("_schedule", "_master"),
    indicator=True
)

print(staff_check["_merge"].value_counts())

matched = staff_check[staff_check["_merge"] == "both"]

print("Role mismatches:",
      (matched["role_schedule"] != matched["role_master"]).sum())

print("Service mismatches:",
      (matched["service_schedule"] != matched["service_master"]).sum())

_merge
both          5720
left_only      832
right_only       0
Name: count, dtype: int64
Role mismatches: 3744
Service mismatches: 1924

In [40]:
staff_summary = staff.groupby("service").agg(
    staff_count=("staff_id", "nunique")
).reset_index()

staff_weekly = schedule.groupby(
    ["week", "service"]
).agg(
    staff_present=("present", "sum")
).reset_index()

hospital_raw = services.merge(
    patient_summary,
    on=["week", "service"],
    how="left"
)

hospital_raw = hospital_raw.merge(
    staff_weekly,
    on=["week", "service"],
    how="left"
)

hospital_raw = hospital_raw.merge(
    staff_summary,
    on="service",
    how="left"
)

print("Integrated shape:", hospital_raw.shape)
print(hospital_raw.head())

Integrated shape: (208, 16)
   week  month           service  available_beds  patients_request  \
0     1      1         emergency              32                76
1     1      1           surgery              45               130
2     1      1  general_medicine              37               201
3     1      1               ICU              22                31
4     2      1         emergency              28               169

   patients_admitted  patients_refused  patient_satisfaction  staff_morale  \
0                 32                44                    67            70
1                 45                85                    83            78
2                 37               164                    97            43
3                 22                 9                    84            91
4                 28               141                    75            64

  event  patient_count  average_age  average_length_of_stay  \
0  none              4    42.250000                9.250000
1   flu              6    50.000000               10.000000
2   flu              5    51.200000                7.400000
3   flu              7    43.000000                5.428571
4  none              3    58.333333                6.000000

   average_satisfaction  staff_present  staff_count
0             86.000000             35           29
1             84.666667             23           22
2             77.400000             27           27
3             84.857143             31           32
4             74.000000             37           29

In [41]:
print("Missing values:")
print(hospital_raw.isnull().sum())

print("\nDuplicate rows:")
print(hospital_raw.duplicated().sum())

print("\nDataset shape:")
print(hospital_raw.shape)

Missing values:
week                      0
month                     0
service                   0
available_beds            0
patients_request          0
patients_admitted         0
patients_refused          0
patient_satisfaction      0
staff_morale              0
event                     0
patient_count             0
average_age               0
average_length_of_stay    0
average_satisfaction      0
staff_present             0
staff_count               0
dtype: int64

Duplicate rows:
0

Dataset shape:
(208, 16)

In [42]:
hospital_raw.to_csv("hospital_raw_data.csv", index=False)