In [1]:
import pandas as pd
import numpy as np
import os

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# Load the hospital raw dataset

data_path = "../data/hospital_raw_data.csv"

df = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 500
Columns: 10

In [3]:
df.head()

,patient_id,age,gender,blood_pressure,heart_rate,cholesterol_level,bmi,diagnosis,treatment_plan,follow_up_date
0,1,51,Female,97,90,282,35.2,Hypertension,Observation,2024-01-01
1,2,92,Other,129,80,169,32.3,Healthy,Medication,2024-01-02
2,3,14,Male,172,76,157,29.9,Diabetes,Observation,2024-01-03
3,4,71,Female,131,82,150,19.4,Coronary Artery Disease,Surgery,2024-01-04
4,5,60,Male,130,96,206,39.3,Diabetes,NaN,2024-01-05

In [4]:
# Missing value analysis

missing_values = df.isnull().sum()

missing_percentage = (missing_values / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

missing_report = missing_report[
    missing_report["Missing Values"] > 0
]

missing_report

                Missing Values  Missing Percentage
treatment_plan              95                19.0

In [5]:
# Visual summary of missing values

print("Total missing values:", df.isnull().sum().sum())
print("\nMissing values by column:")
print(df.isnull().sum())

Total missing values: 95

Missing values by column:
patient_id            0
age                   0
gender                0
blood_pressure        0
heart_rate            0
cholesterol_level     0
bmi                   0
diagnosis             0
treatment_plan       95
follow_up_date        0
dtype: int64

In [6]:
# Handle missing treatment plans

missing_before = df["treatment_plan"].isnull().sum()

print("Missing treatment plans before cleaning:", missing_before)

df["treatment_plan"] = df["treatment_plan"].fillna("Not Specified")

missing_after = df["treatment_plan"].isnull().sum()

print("Missing treatment plans after cleaning:", missing_after)

Missing treatment plans before cleaning: 95
Missing treatment plans after cleaning: 0

In [7]:
# Verify missing values after treatment

print("Total missing values after cleaning:")
print(df.isnull().sum().sum())

print("\nMissing values by column:")
print(df.isnull().sum())

Total missing values after cleaning:
0

Missing values by column:
patient_id           0
age                  0
gender               0
blood_pressure       0
heart_rate           0
cholesterol_level    0
bmi                  0
diagnosis            0
treatment_plan       0
follow_up_date       0
dtype: int64

In [8]:
# Calculate dataset completeness

total_cells = df.shape[0] * df.shape[1]
missing_cells = df.isnull().sum().sum()

completeness = ((total_cells - missing_cells) / total_cells) * 100

print(f"Dataset completeness: {completeness:.2f}%")

Dataset completeness: 100.00%

In [9]:
# Check data types

print("Data types of each column:\n")

print(df.dtypes)

Data types of each column:

patient_id             int64
age                    int64
gender                   str
blood_pressure         int64
heart_rate             int64
cholesterol_level      int64
bmi                  float64
diagnosis                str
treatment_plan           str
follow_up_date           str
dtype: object

In [10]:
# Check basic statistical information

df.describe(include="all")

,patient_id,age,gender,blood_pressure,heart_rate,cholesterol_level,bmi,diagnosis,treatment_plan,follow_up_date
count,500.000000,500.00000,500,500.000000,500.000000,500.000000,500.000000,500,500,500
unique,NaN,NaN,3,NaN,NaN,NaN,NaN,5,5,500
top,NaN,NaN,Male,NaN,NaN,NaN,NaN,Healthy,Medication,2024-01-01
freq,NaN,NaN,187,NaN,NaN,NaN,NaN,104,109,1
mean,250.500000,48.87400,NaN,133.024000,79.874000,225.806000,29.430400,NaN,NaN,NaN
std,144.481833,29.56983,NaN,25.665246,11.354293,44.964608,6.132838,NaN,NaN,NaN
min,1.000000,0.00000,NaN,90.000000,60.000000,150.000000,18.600000,NaN,NaN,NaN
25%,125.750000,23.00000,NaN,112.000000,70.750000,186.000000,24.100000,NaN,NaN,NaN
50%,250.500000,50.00000,NaN,132.000000,79.500000,226.000000,29.600000,NaN,NaN,NaN
75%,375.250000,72.25000,NaN,154.000000,90.000000,267.000000,34.725000,NaN,NaN,NaN
max,500.000000,99.00000,NaN,179.000000,99.000000,299.000000,40.000000,NaN,NaN,NaN

In [11]:
# Check unique values in categorical columns

print("Gender values:")
print(df["gender"].unique())

print("\nDiagnosis values:")
print(df["diagnosis"].unique())

print("\nTreatment plan values:")
print(df["treatment_plan"].unique())

Gender values:
<StringArray>
['Female', 'Other', 'Male']
Length: 3, dtype: str

Diagnosis values:
<StringArray>
[           'Hypertension',                 'Healthy',
                'Diabetes', 'Coronary Artery Disease',
          'Hyperlipidemia']
Length: 5, dtype: str

Treatment plan values:
<StringArray>
['Observation', 'Medication', 'Surgery', 'Not Specified', 'Lifestyle Changes']
Length: 5, dtype: str

In [12]:
print(df.dtypes)

patient_id             int64
age                    int64
gender                   str
blood_pressure         int64
heart_rate             int64
cholesterol_level      int64
bmi                  float64
diagnosis                str
treatment_plan           str
follow_up_date           str
dtype: object

In [13]:
# Check duplicate records

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [14]:
# Check for duplicate patient IDs

duplicate_patient_ids = df["patient_id"].duplicated().sum()

print("Duplicate patient IDs:", duplicate_patient_ids)

Duplicate patient IDs: 0

In [15]:
# Convert follow-up date to datetime

df["follow_up_date"] = pd.to_datetime(
    df["follow_up_date"],
    errors="coerce"
)

print("Follow-up date data type:")
print(df["follow_up_date"].dtype)

Follow-up date data type:
datetime64[us]

In [16]:
# Check missing values after date conversion

print(
    "Missing follow-up dates:",
    df["follow_up_date"].isnull().sum()
)

Missing follow-up dates: 0

In [17]:
# Check numerical healthcare indicators

numeric_columns = [
    "age",
    "blood_pressure",
    "heart_rate",
    "cholesterol_level",
    "bmi"
]

df[numeric_columns].describe()

             age  blood_pressure  heart_rate  cholesterol_level         bmi
count  500.00000      500.000000  500.000000         500.000000  500.000000
mean    48.87400      133.024000   79.874000         225.806000   29.430400
std     29.56983       25.665246   11.354293          44.964608    6.132838
min      0.00000       90.000000   60.000000         150.000000   18.600000
25%     23.00000      112.000000   70.750000         186.000000   24.100000
50%     50.00000      132.000000   79.500000         226.000000   29.600000
75%     72.25000      154.000000   90.000000         267.000000   34.725000
max     99.00000      179.000000   99.000000         299.000000   40.000000

In [18]:
# Check for impossible or suspicious values

print("Age range:")
print(df["age"].min(), "to", df["age"].max())

print("\nBlood pressure range:")
print(df["blood_pressure"].min(), "to", df["blood_pressure"].max())

print("\nHeart rate range:")
print(df["heart_rate"].min(), "to", df["heart_rate"].max())

print("\nCholesterol range:")
print(df["cholesterol_level"].min(), "to", df["cholesterol_level"].max())

print("\nBMI range:")
print(df["bmi"].min(), "to", df["bmi"].max())

Age range:
0 to 99

Blood pressure range:
90 to 179

Heart rate range:
60 to 99

Cholesterol range:
150 to 299

BMI range:
18.6 to 40.0

In [19]:
# Check numerical healthcare indicators

numeric_columns = [
    "age",
    "blood_pressure",
    "heart_rate",
    "cholesterol_level",
    "bmi"
]

df[numeric_columns].describe()

             age  blood_pressure  heart_rate  cholesterol_level         bmi
count  500.00000      500.000000  500.000000         500.000000  500.000000
mean    48.87400      133.024000   79.874000         225.806000   29.430400
std     29.56983       25.665246   11.354293          44.964608    6.132838
min      0.00000       90.000000   60.000000         150.000000   18.600000
25%     23.00000      112.000000   70.750000         186.000000   24.100000
50%     50.00000      132.000000   79.500000         226.000000   29.600000
75%     72.25000      154.000000   90.000000         267.000000   34.725000
max     99.00000      179.000000   99.000000         299.000000   40.000000

In [20]:
# Check minimum and maximum values

for column in numeric_columns:
    print(f"\n{column}")
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())

age
Minimum: 0
Maximum: 99

blood_pressure
Minimum: 90
Maximum: 179

heart_rate
Minimum: 60
Maximum: 99

cholesterol_level
Minimum: 150
Maximum: 299

bmi
Minimum: 18.6
Maximum: 40.0

In [21]:
# Standardize categorical text values

text_columns = [
    "gender",
    "diagnosis",
    "treatment_plan"
]

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

# Standardize capitalization
df["gender"] = df["gender"].str.title()
df["diagnosis"] = df["diagnosis"].str.title()
df["treatment_plan"] = df["treatment_plan"].str.title()

print("Categorical values standardized successfully.")

Categorical values standardized successfully.

In [22]:
# Final duplicate validation

print("Duplicate rows:", df.duplicated().sum())
print("Duplicate patient IDs:", df["patient_id"].duplicated().sum())

Duplicate rows: 0
Duplicate patient IDs: 0

In [23]:
# Final missing-value validation

missing_total = df.isnull().sum().sum()
total_cells = df.shape[0] * df.shape[1]

missing_percentage = (missing_total / total_cells) * 100
completeness = 100 - missing_percentage

print("Total missing values:", missing_total)
print(f"Missing percentage: {missing_percentage:.2f}%")
print(f"Dataset completeness: {completeness:.2f}%")

Total missing values: 0
Missing percentage: 0.00%
Dataset completeness: 100.00%

In [24]:
# Save final Tableau-ready dataset

output_path = "../data/hospital_cleaned.csv"

df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File:", output_path)

Cleaned dataset saved successfully!
File: ../data/hospital_cleaned.csv

In [25]:
# Preview the cleaned dataset

df.head()

,patient_id,age,gender,blood_pressure,heart_rate,cholesterol_level,bmi,diagnosis,treatment_plan,follow_up_date
0,1,51,Female,97,90,282,35.2,Hypertension,Observation,2024-01-01
1,2,92,Other,129,80,169,32.3,Healthy,Medication,2024-01-02
2,3,14,Male,172,76,157,29.9,Diabetes,Observation,2024-01-03
3,4,71,Female,131,82,150,19.4,Coronary Artery Disease,Surgery,2024-01-04
4,5,60,Male,130,96,206,39.3,Diabetes,Not Specified,2024-01-05

In [26]:
# Final dataset dimensions

print("Final rows:", df.shape[0])
print("Final columns:", df.shape[1])

Final rows: 500
Final columns: 10