In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()

Saving hospital_raw_data.csv to hospital_raw_data.csv

In [3]:
df = pd.read_csv("hospital_raw_data.csv")

df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 55500
Columns: 15
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [16]:
print(df.columns.tolist())

['name', 'age', 'gender', 'blood_type', 'medical_condition', 'date_of_admission', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results']

In [5]:
df.describe(include="all")

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
count,55500,55500.000000,55500,55500,55500,55500,55500,55500,55500,55500.000000,55500.000000,55500,55500,55500,55500
unique,49992,NaN,2,8,6,1827,40341,39876,5,NaN,NaN,3,1856,5,3
top,DAvId muNoZ,NaN,Male,A-,Arthritis,2024-03-16,Michael Smith,LLC Smith,Cigna,NaN,NaN,Elective,2020-03-15,Lipitor,Abnormal
freq,3,NaN,27774,6969,9308,50,27,44,11249,NaN,NaN,18655,53,11140,18627
mean,NaN,51.539459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25539.316097,301.134829,NaN,NaN,NaN,NaN
std,NaN,19.602454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14211.454431,115.243069,NaN,NaN,NaN,NaN
min,NaN,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2008.492140,101.000000,NaN,NaN,NaN,NaN
25%,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13241.224652,202.000000,NaN,NaN,NaN,NaN
50%,NaN,52.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25538.069376,302.000000,NaN,NaN,NaN,NaN
75%,NaN,68.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37820.508436,401.000000,NaN,NaN,NaN,NaN
max,NaN,89.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52764.276736,500.000000,NaN,NaN,NaN,NaN

In [17]:
display(df.head())

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [18]:
print("Duplicate rows before cleaning:", df.duplicated().sum())

Duplicate rows before cleaning: 0

In [19]:
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [20]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df.columns.tolist())

['name', 'age', 'gender', 'blood_type', 'medical_condition', 'date_of_admission', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results']

In [22]:
total_cells = df.shape[0] * df.shape[1]
missing_cells = df.isnull().sum().sum()

missing_percentage = (missing_cells / total_cells) * 100

print("Overall missing percentage:", round(missing_percentage, 2), "%")

Overall missing percentage: 0.0 %

In [23]:
print("Gender:")
print(df["gender"].value_counts())

print("\nBlood Type:")
print(df["blood_type"].value_counts())

print("\nMedical Condition:")
print(df["medical_condition"].value_counts())

print("\nAdmission Type:")
print(df["admission_type"].value_counts())

print("\nMedication:")
print(df["medication"].value_counts())

print("\nTest Results:")
print(df["test_results"].value_counts())

Gender:
gender
Male      27496
Female    27470
Name: count, dtype: int64

Blood Type:
blood_type
A-     6898
A+     6896
B+     6885
AB+    6882
AB-    6874
B-     6872
O+     6855
O-     6804
Name: count, dtype: int64

Medical Condition:
medical_condition
Arthritis       9218
Diabetes        9216
Hypertension    9151
Obesity         9146
Cancer          9140
Asthma          9095
Name: count, dtype: int64

Admission Type:
admission_type
Elective     18473
Urgent       18391
Emergency    18102
Name: count, dtype: int64

Medication:
medication
Lipitor        11038
Ibuprofen      11023
Aspirin        10984
Paracetamol    10965
Penicillin     10956
Name: count, dtype: int64

Test Results:
test_results
Abnormal        18437
Normal          18331
Inconclusive    18198
Name: count, dtype: int64

In [25]:
text_columns = [
    "name",
    "gender",
    "blood_type",
    "medical_condition",
    "doctor",
    "hospital",
    "insurance_provider",
    "admission_type",
    "medication",
    "test_results"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [27]:
df["gender"] = df["gender"].str.title()

In [28]:
df["medical_condition"] = df["medical_condition"].str.title()
df["admission_type"] = df["admission_type"].str.title()
df["medication"] = df["medication"].str.title()
df["test_results"] = df["test_results"].str.title()
df["insurance_provider"] = df["insurance_provider"].str.title()

In [29]:
df["date_of_admission"] = pd.to_datetime(
    df["date_of_admission"],
    errors="coerce"
)

df["discharge_date"] = pd.to_datetime(
    df["discharge_date"],
    errors="coerce"
)

In [30]:
print(df[["date_of_admission", "discharge_date"]].dtypes)

date_of_admission    datetime64[ns]
discharge_date       datetime64[ns]
dtype: object

In [31]:
print(df[["date_of_admission", "discharge_date"]].dtypes)

date_of_admission    datetime64[ns]
discharge_date       datetime64[ns]
dtype: object

In [32]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["billing_amount"] = pd.to_numeric(df["billing_amount"], errors="coerce")
df["room_number"] = pd.to_numeric(df["room_number"], errors="coerce")

In [33]:
print(df.isnull().sum())

name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
dtype: int64

In [34]:
numeric_columns = [
    "age",
    "billing_amount",
    "room_number"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [36]:
categorical_columns = [
    "gender",
    "blood_type",
    "medical_condition",
    "admission_type",
    "medication",
    "test_results",
    "insurance_provider"
]

for col in categorical_columns:
    df[col] = df[col].fillna("Unknown")

In [37]:
print("Missing admission dates:",
      df["date_of_admission"].isnull().sum())

print("Missing discharge dates:",
      df["discharge_date"].isnull().sum())

Missing admission dates: 0
Missing discharge dates: 0

In [38]:
df["length_of_stay"] = (
    df["discharge_date"] - df["date_of_admission"]
).dt.days

In [40]:
df["length_of_stay"].describe()

count    54966.000000
mean        15.499290
std          8.661471
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: length_of_stay, dtype: float64

In [41]:
print(
    "Negative length of stay:",
    (df["length_of_stay"] < 0).sum()
)

Negative length of stay: 0

In [42]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("Duplicate rows:", df.duplicated().sum())

print("Total missing values:", df.isnull().sum().sum())

total_cells = df.shape[0] * df.shape[1]
missing_cells = df.isnull().sum().sum()

missing_percentage = (missing_cells / total_cells) * 100

print("Missing percentage:",
      round(missing_percentage, 2), "%")

========== FINAL DATA QUALITY CHECK ==========
Rows: 54966
Columns: 16
Duplicate rows: 0
Total missing values: 0
Missing percentage: 0.0 %

In [43]:
display(df.head(10))

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,Unitedhealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal,4
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive,12
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive,10
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal,13
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,Unitedhealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive,30

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                54966 non-null  object
 1   age                 54966 non-null  int64
 2   gender              54966 non-null  object
 3   blood_type          54966 non-null  object
 4   medical_condition   54966 non-null  object
 5   date_of_admission   54966 non-null  datetime64[ns]
 6   doctor              54966 non-null  object
 7   hospital            54966 non-null  object
 8   insurance_provider  54966 non-null  object
 9   billing_amount      54966 non-null  float64
 10  room_number         54966 non-null  int64
 11  admission_type      54966 non-null  object
 12  discharge_date      54966 non-null  datetime64[ns]
 13  medication          54966 non-null  object
 14  test_results        54966 non-null  object
 15  length_of_stay      54966 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(10)
memory usage: 9.1+ MB

In [45]:
df.to_csv(
    "hospital_cleaned.csv",
    index=False
)

print("hospital_cleaned.csv created successfully!")

hospital_cleaned.csv created successfully!

In [46]:
files.download("hospital_cleaned.csv")